AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cmart random artwork

Globals:
  Function:
    Timeout: 5

Resources:
  CmartLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap 
      Runtime: provided.al2
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: '*'
    Metadata:
      BuildMethod: makefile
